### ISSUE TITLE
PyOSRA work...

### ISSUE THREAD

**Issue by yichunli95** [Kohulan/OCSR_Review#1]
Hello!
I am working on a project related to chemical recognition and also saw the PyOSRA package but I got no luck with installing the package. Which installation approach did you use? Which OS platform were you doing this on?
Thank you!

**Comment by OBrink** [comment]
Hey there! 

The easiest way to install PyOsra probably is to install ChemSchematicResolver via Anaconda. ([ChemSchematicResolver Documentation](https://www.chemschematicresolver.org/docs/install)).

We installed it based on the [PyOsra Conda recipe by Ed Beard](https://github.com/edbeard/conda_recipes) on Ubuntu 20.04. The [ChemSchematicResolver Documentation](https://www.chemschematicresolver.org/docs/install) also includes an instruction about how to work with Conda recipes.

Kind regards,

Otto
